[server]
headless = true
enableCORS = false
port = 8501
fileWatcherType = "poll"

[theme]
primaryColor = "#E74C3C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
